### ISSUE TITLE
Split out template.py into separate modules

### ISSUE THREAD

**Issue by mrlesmithjr** [mrlesmithjr/packer-builder#58]
In an effort to slim down `template.py` we should split out into builder specs structure.

Will look similar to:
```bash
packer_builder/specs
├── __init__.py
├── builders
│   ├── __init__.py
│   ├── common.py
│   ├── distro.py
│   ├── distros
│   │   ├── __init__.py
│   │   ├── alpine.py
│   │   ├── centos.py
│   │   ├── debian.py
│   │   ├── fedora.py
│   │   ├── freenas.py
│   │   └── ubuntu.py
│   ├── qemu.py
│   ├── virtualbox.py
│   └── vmware.py
└── provisioners
    ├── __init__.py
    ├── freenas.py
    ├── linux.py
    └── windows.py
```

We may still work towards #4 after this but for now I want to explore this route.

**Comment by mrlesmithjr** [comment]
Paging @bunchc for thoughts! :)

**Comment by bunchc** [comment]
I like this idea. Also makes things a bit more modular to ease adding additional builders (hyperv, etc)

**Comment by mrlesmithjr** [comment]
Yeah that is what I was thinking as well. Which is the route I was attempting to go. I have this all ready to be merged. Want to review? :)
