### ISSUE TITLE
Add functionality to emit `template.json` withour running a build

### ISSUE THREAD

**Issue by bunchc** [mrlesmithjr/packer-builder#6]
In addition to being a power Packer build runner, we have a power `template.json` generator as well. At this time, producing a template requires running a build. However, we should be able to emit a template without a build as well.

To produce a template, I suggest adding a `template` run-time action. This action would accept the same parameters as the existing `build` action, but would stop after the `self.validate()` step in `build.py`

**Comment by mrlesmithjr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add functionality to emit `template.json` withour running a build](https://trello.com/c/eJhOH9tl/6-add-functionality-to-emit-templatejson-withour-running-a-build)
